version: '3'

services:
  db:
    image: mariadb:11
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
    networks:
      - wordpress_net

  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE_NAME}
    volumes:
      - wordpress_data:/var/www/html
      - ./.well-known:/var/www/html/.well-known
      - ./config/php.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wordpress_net

volumes:
  db_data:
  wordpress_data:

networks:
  wordpress_net:
    driver: bridge