version: '3.9'
services:
  db:
    image: mariadb
    container_name: wp_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  wordpress-fpm:
    image: wordpress:6-fpm-alpine
    container_name: wordpress
    links:
      - db
    volumes:
      - wp_files:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE_NAME}

  nginx:
    image: nginx:alpine
    container_name: wp-nginx
    depends_on:
      - wordpress-fpm
    ports:
      - 80:80    # http
      - 443:443   # https
    volumes:
      - wp_files:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl:ro
      - ./logs/nginx:/var/log/nginx

volumes:
  wp_files:
  db_data: